package main;
import javax.swing.*;
import java.util.ArrayList;


// Fiction for kids branch
rule "genre-kidfic"
when
    ans: Odpowiedz(pytanie == Pytania.FICTION_TYPE, wybor == "Fiction for kids");
then
    insert(Pytania.AGE);
end


rule "age-kid"
when
    ans: Odpowiedz(pytanie == Pytania.AGE, wybor == "Children below 12");
then
    insert(Pytania.KIDS_TYPE);
end


rule "age-teen"
when
    ans: Odpowiedz(pytanie == Pytania.AGE, wybor == "Teen 12-17");
then
    insert(Pytania.TEEN_TYPE);
end


rule "age-youngadult"
when
    ans: Odpowiedz(pytanie == Pytania.AGE, wybor == "Young Adults over 17");
then
    insert(Pytania.ADULTS_TYPE);
end


rule "kid-coming of age"
when
    ans: Odpowiedz(pytanie == Pytania.KIDS_TYPE, wybor == "Coming of age");
then
    insert(new Wynik("Wonder by R.J. Palacio"));
end


rule "kid-thriller"
when
    ans: Odpowiedz(pytanie == Pytania.KIDS_TYPE, wybor == "Thriller");
then
    insert(new Wynik("The Lightning Thief by Rick Riordan"));
end


rule "kid-peril"
when
    ans: Odpowiedz(pytanie == Pytania.KIDS_TYPE, wybor == "Peril");
then
    insert(new Wynik("A Series of Unfortunate Events: The End by Lemony Snicket"));
end


rule "kid-fantasy"
when
    ans: Odpowiedz(pytanie == Pytania.KIDS_TYPE, wybor == "Fantasy");
then
    insert(new Wynik
        ("Harry Potter and the Deathly Hallows by J.K. Rowling\n" +
         "Coraline by Neil Gaiman\n" +
         "The Graveyard Book by Neil Gaiman"));
end


rule "teen-historical"
when
    ans: Odpowiedz(pytanie == Pytania.TEEN_TYPE, wybor == "Historical");
then
    insert(new Wynik("Clockwork Angel by Cassandra Clare"));
end


rule "teen-thriller"
when
    ans: Odpowiedz(pytanie == Pytania.TEEN_TYPE, wybor == "Thriller");
then
    insert(new Wynik("The Hunger Games by Suzanne Collins"));
end


rule "teen-fantasy"
when
    ans: Odpowiedz(pytanie == Pytania.TEEN_TYPE, wybor == "Fantasy");
then
    insert(new Wynik
        ("Eragon by Christopher Paolini\n" +
         "Insurgent by Veronica Roth\n" +
         "City of Bones by Cassandra Clare"));
end


rule "teen-relationships"
when
    ans: Odpowiedz(pytanie == Pytania.TEEN_TYPE, wybor == "Relationships");
then
    insert(new Wynik
        ("The Fault in Our Stars by John Green\n" +
         "Looking for Alaska by John Green"));
end


rule "teen-vampires" // XD
when
    ans: Odpowiedz(pytanie == Pytania.TEEN_TYPE, wybor == "Vampires");
then
    insert(new Wynik
        ("Twillight by Stephenie Meyer\n" +
         "Vampire Academy by Richelle Mead"));
end


rule "adults-historical"
when
    ans: Odpowiedz(pytanie == Pytania.ADULTS_TYPE, wybor == "A historical one");
then
    insert(new Wynik("Diary of a Wimpy Kid by Jeff Kinney"));
end


rule "adults-comedy"
when
    ans: Odpowiedz(pytanie == Pytania.ADULTS_TYPE, wybor == "A comedy, please");
then
    insert(new Wynik("The Book Thief by Markus Zusak"));
end
