package main;
import javax.swing.*;
import java.util.ArrayList;


 // Literary fiction branch


rule "genre-Literary-fiction"
when
    ans: Odpowiedz(pytanie == Pytania.FICTION_TYPE, wybor == "Literary fiction");
then
    insert(Pytania.DYSTOPIA);
end

rule "DYSTOPIA-yes"
when
    ans: Odpowiedz(pytanie == Pytania.DYSTOPIA, wybor == "Yes");
then
    insert(Pytania.FANTASY);
end

rule "DYSTOPIA-no"
when
    ans: Odpowiedz(pytanie == Pytania.DYSTOPIA, wybor == "No");
then
    insert(Pytania.FANTASY);
end

//rule "FANTASY"
//when
//    ans: Odpowiedz(pytanie == Pytania.DYSTOPIA, wybor == "Popular fiction");
//then
//    insert(Pytania.THRILLER);
//end