package main;
import javax.swing.*;
import java.util.ArrayList;

global JFrame okno;


declare enum Pytania
    FICTION_TYPE("What type of fiction you'd like?",
        ["Popular fiction",
         "Literary fiction",
         "Fiction for kids",
         "Non-fiction",
         "Self-help book"
         ]),

        // Popular fiction branch
        THRILLER("Would you like an intense thriller?",
            ["Yes", "No"]),

        MYSTERY("How about a mystery book?",
            ["Sure", "I'd go for something else"]),

        FAMILY("Maybe you are in mood for a family book?",
            ["Why not?", "Nah"]),

        FAN_HORROR("Then maybe you'd enjoy a fantasy horror book?",
            ["Bring it on", "Better not"]),

        ROMANCE("Would you like an intense Romance?",
            ["Yes", "No"]),

        TIME_OR_SUSPENSE("Time travel or maybe some book that keeps in suspense?",
            ["Time travel",
             "Suspense"]),

        // Literary fiction branch

        DYSTOPIA("Would you like to read some dystopia positions?",
                 ["Yes", "No"]),

        FANTASY("Then maybe some Fantasy?",
                 ["Sure", "No"]),

        IDENTITY("Would you like to some Identity books?",
                 ["Why not?", "No"]),

        MAGICAL_REALISM("How about Magical Realism?",
                 ["Yep", "Nope"]),

        COMIC("Would you like to smile with comic book?",
                 ["Bring it on", "Better not"]),

        CRIME("Would you like to read some crime positions?",
                 ["Yes", "No"]),

        HISTORY("How about history literature?",
                 ["Ok", "No"]),

        FAMILY_LITERARY("Maybe you are in mood for a family book?",
                 ["Sure", "Nope"]),

        MYSTERY_LITERARY("Looking for Mystery?",
                 ["YES !", "Definitly No"]),
            MYSTERY_LITERARY_TYPE("Which type of mystery?",
                     ["Literary", "Suspense"]),

        BASEBALL("Do you want to know more about baseball?",
                 ["Of course", "No"]),

        CULTURE_OR_FANTASY("Would you like to discover new cultures?",
                 ["Yes", "No"]),
            NEW_CULTURE_TYPE    ("Which topic is interesting for you?",
                     ["Civil rights", "Epistolary", "Japan", "Historical",
                      "Romance", "War"]),

        FANTASY_TYPE("Eventually you have to choose fantasy book. Which topic is the most interesting?",
                 ["Epic", "Video games", "Vampires", "Historical", "Magic",
                  "Literary", "Romance"]),

        // Fiction for Kids branch

        YOUNG_ADULTS("Do you want literature for young adults?",
                 ["Yeah", "Nope"]),

        CHILDREN_OR_TEEN("Do you want literature for children or teens?",
                 ["Children", "Teen"]),

        TEEN_TYPE("Then, what is your favourite type of teen book?",
            ["Historical",
             "Thriller",
             "Fantasy",
             "Relationships",
             "Vampires"]),

        KIDS_TYPE("What type of stories do you like the most?",
            ["Coming of age",
             "Thriller",
             "Peril",
             "Fantasy"]),

        ADULTS_TYPE("What do you prefer?", ["A historical one", "A comedy, please"]),

        // Nonfiction

        MEMOIRS("Would you like to read a memoir?", ["Yeah", "I'd go for something else"]),
            MEMO_TYPE("What type of memoir?",
                ["Family",
                 "Humor",
                 "Medical",
                 "Current events",
                 "Self-fulfillment"]),

        FOOD("Maybe fancy reading a story about food?",  ["Why not?", "No"]),

        BUSINESS("Would you like a business book then?", ["Yes", "No"]),

        BIOGRAPHY("What about a biography?", ["Yeah", "Nope"]),

        GRAMMAR("A grammar-related story?", ["Why not?", "I'd go for something else"]),

        HISTORY_NONFICTION("Then maybe something about history?", ["Ok", "Not this time"]),

        HUMOR("What about book with humor?", ["Yes", "Yes, but actually no"]),

        INSPIRATION("Would you like a inspirational book ?", ["Lovely!", "Nope"]),

        US_GOVERNMENT_OR_NUTRITION("Now you have to make decision between U.S.Government and Nutrition theme. Choose wisely !
        ", ["U.S. Government", "Nutrition"]),

        // Self-Help branch
        RELATIONSHIP("Would you like a relationship story?", ["Yes", "No"]),

        INSPIRATIONAL_OR_BUSINESS("Would you like a book about business or maybe inspirational one?",
            ["Inspirational",
             "Business"]);



    tresc: String
    opcje: ArrayList
end;


declare Odpowiedz
    pytanie : Pytania @key
    wybor: String
end


declare Wynik
    odpowiedz: String
end


rule "Odpytywajnik"
when
    q: Pytania();
then
    Object[] opcje = q.getOpcje().toArray();
    int ans = JOptionPane.showOptionDialog(okno, q.getTresc(), "", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcje, 1);

    if(ans != JOptionPane.CLOSED_OPTION) {
        Odpowiedz odpowiedz = new Odpowiedz(q, (String)opcje[ans]);
       	insert(odpowiedz);
    }
end


rule "Odpowiedz"
when
    w: Wynik();
then
    JOptionPane.showMessageDialog(okno, "Books recommended for you: \n" + w.getOdpowiedz());
end


rule "Init"
when
then
    insert(Pytania.FICTION_TYPE);
end
