package main;
import javax.swing.*;
import java.util.ArrayList;


// Pop fiction branch
rule "genre-popfic"
when
    ans: Odpowiedz(pytanie == Pytania.FICTION_TYPE, wybor == "Popular fiction");
then
    insert(Pytania.THRILLER);
end

rule "thriller-yes"
when
    ans: Odpowiedz(pytanie == Pytania.THRILLER, wybor == "Yes");
then
    insert(new Wynik
        ("Before I Go To Sleep by S.J. Watson \n" +
         "Nineteen Minutes by Jodi Picoult\n" +
         "The Girl with the Dragon Tatoo by Stieg Larsson"));
end


rule "thriller-no"
when
    ans: Odpowiedz(pytanie == Pytania.THRILLER, wybor == "No");
then
    insert(Pytania.MYSTERY);
end


rule "mystery-yes"
when
    ans: Odpowiedz(pytanie == Pytania.MYSTERY, wybor == "Sure");
then
    insert(new Wynik
        ("The Lovely Bones by Alice Sebold\n" +
         "The Thirteenth Tale by Diane Setterfield"));
end


rule "mystery-no"
when
    ans: Odpowiedz(pytanie == Pytania.MYSTERY, wybor == "I'd go for something else");
then
    insert(Pytania.FAMILY);
end


rule "family-yes"
when
    ans: Odpowiedz(pytanie == Pytania.FAMILY, wybor == "Why not?")
then
    insert(new Wynik
        ("Room by Emma Donghue\n" +
         "My Sister's Keeper by Jodi Picoult\n" +
         "The Memory Keeper's Daughter by Kim Edwards\n" +
         "The Language of Flowers by Vanessa Diffenbaugh"));
end


rule "family-no"
when
    ans: Odpowiedz(pytanie == Pytania.FAMILY, wybor == "Nah");
then
    insert(Pytania.FAN_HORROR);
end


rule "fanhorror-yes"
when
    ans: Odpowiedz(pytanie == Pytania.FAN_HORROR, wybor == "Bring it on");
then
    insert(new Wynik("The Historian by Elizabeth Kostova"));
end


rule "fanhorror-nope"
when
    ans: Odpowiedz(pytanie == Pytania.FAN_HORROR, wybor == "Better not");
then
    insert(Pytania.ROMANCE);
end

rule "ROMANCE-Yes"
when
    ans: Odpowiedz(pytanie == Pytania.ROMANCE, wybor == "Yes");
then
    insert(new Wynik(
        "The Other Boleyn Girl by Philippa Gregory\n" +
        "Snow Flower and the Secret Fan by Lisa See"));
end

rule "ROMANCE-No"
when
    ans: Odpowiedz(pytanie == Pytania.ROMANCE, wybor == "No");
then
    insert(Pytania.TIME_OR_SUSPENSE);
end


rule "TIME_OR_SUSPENSE-Time travel"
when
    ans: Odpowiedz(pytanie == Pytania.TIME_OR_SUSPENSE, wybor == "Time travel");
then
    insert(new Wynik
        ("The Time Traveller's Wife by Audrey Niffenegger\n" +
         "11/22/63 by Stephen King"));
end


rule "TIME_OR_SUSPENSE-Suspense"
when
    ans: Odpowiedz(pytanie == Pytania.TIME_OR_SUSPENSE, wybor == "Suspense");
then
    insert(new Wynik
        ("Gone Girl by Gillian Flynn\n" +
         "The Da Vinci Code by Dan Brown\n" +
         "Joyland by Stephen King"));
end
