package main;
import javax.swing.*;
import java.util.ArrayList;


// Self help branch
rule "genre-self help"
when
    ans: Odpowiedz(pytanie == Pytania.FICTION_TYPE, wybor == "Self-help book");
then
    insert(Pytania.RELATIONSHIP);
end


rule "RELATIONSHIP-Yes"
when
    ans: Odpowiedz(pytanie == Pytania.RELATIONSHIP, wybor == "Yes");
then
    insert(new Wynik
        ("Quiet: The Power of Introverts in a World that Can't Stop Talking by Susan Cain"));
end

rule "RELATIONSHIP-No"
when
    ans: Odpowiedz(pytanie == Pytania.RELATIONSHIP, wybor == "No");
then
    insert(Pytania.INSPIRATIONAL_OR_BUSINESS);
end


rule "INSPIRATIONAL_OR_BUSINESS-inspirational"
when
    ans: Odpowiedz(pytanie == Pytania.INSPIRATIONAL_OR_BUSINESS, wybor == "Inspirational");
then
    insert(new Wynik
        ("The Five People you Meet in Heaven by Mitch Albom\n" +
         "Daring Greatly: How the Courage to Be Vurnelable Transforms the Way We Live," +
         "Love, Parent and Lead by Brene Brown"));
end


rule "INSPIRATIONAL_OR_BUSINESS-business"
when
    ans: Odpowiedz(pytanie == Pytania.INSPIRATIONAL_OR_BUSINESS, wybor == "Business");
then
    insert(new Wynik
        ("The Five Dysfunctions of a Team by Patrick Lencioni\n" +
         "Strengths Finder 2.0 by Tom Rath\n" +
         "Lean In by Sheryl Sandberg\n" +
         "Good to Great by Jim Collins\n" +
         "The Power of Habit: Why We Do What We Do in Life and Business by Charles Duhigg"));
end